development:
  adapter: mysql2
  encoding: utf8
  database: snapshot_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: snapshot_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock